linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false

output:
  formats:
    - colored-line-number
