version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false

output:
  formats:
    github-actions: true  # ou outro formato desejado
