linters:
  enable:
    - gofmt
    - govet
    - revive
    - gosimple
    - ineffassign
    - misspell
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false

output:
  format: colored-line-number
