name: Go CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop", "release/**"]

permissions:
  pull-requests: read

jobs:
  test:
    name: Test and Quality Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      # Step 3: Cache Go modules
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Verify dependencies
      - name: Verify dependencies
        run: go mod verify

      # Step 5: Build the project
      - name: Build
        run: go build -v ./...

      # Step 6: Run tests
      - name: Run Tests
        run: go test -v -race -p 4 ./...

      # Step 7: Generate coverage report
      - name: Generate Coverage Report
        run: go test -coverprofile=coverage.out ./...

      # Step 8: Run vet
      - name: Run Vet
        run: go vet ./...

      # Step 9: Check formatting
      - name: Check formatting
        run: |
          if [ -n "$(goimports -l .)" ]; then
            echo "These files are not formatted correctly:"
            goimports -l .
            exit 1
          fi

      # Step 10: Run golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2

      # Step 11: Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
